export const ActionTypes = {
  LOGIN: 'LOGIN',
  SIGNOUT: 'SIGNOUT',

  GET_BOOKS: 'GET_BOOKS',
  ADD_BOOK: 'ADD_BOOK',
  EDIT_BOOK: 'EDIT_BOOK',
  REMOVE_BOOK: 'REMOVE_BOOK',

  ADD_AUTHOR: 'ADD_AUTHOR',
  EDIT_AUTHOR: 'EDIT_AUTHOR',
}